# Example GitHub Actions workflow which provides a CI build for your Mbed CE project.

name: Test that test cases compile

on: push

jobs:
  compile:
    runs-on: ubuntu-latest
    container: ghcr.io/armmbed/mbed-os-env:master-latest
    
    strategy:
      matrix:
        mbed_target: 
          # This is just one of the targets supported by these test cases, but it should
          # be sufficient for making sure it compiles
          - NUCLEO_L452RE_P
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Python dependencies
        run: |
            python3 -m pip install -r CI-Shield-Tests/mbed-os/tools/requirements.txt

      - name: Build project for ${{ matrix.mbed_target }}
        run: |
            cd CI-Shield-Tests
            mkdir build && cd build
            cmake .. -GNinja -DMBED_TARGET=${{ matrix.mbed_target }}
            ninja
